spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doday
    username: doday
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: application-secret.yml

server:
  port: 8080